export const REDIS_CONNECTION = {
  url: process.env.REDIS_URL,
};

export const DOWNLOAD_AND_IMPORT_TITLES_QUEUE_NAME = 'download-and-import-titles';
export const FIND_TITLES_QUEUE_NAME = 'find-titles';
export const NORMALIZE_TITLES_QUEUE_NAME = 'normalize-titles';
export const NORMALIZE_TITLES_QUEUE_CONCURRENCY = 100;
export const COMPLEMENT_TITLE_QUEUE_NAME = 'complement-title';
export const COMPLEMENT_TITLES_QUEUE_CONCURRENCY = 10;
export const DOWNLOAD_TORRENT_QUEUE_NAME = 'download-torrent';
export const DOWNLOAD_TORRENT_QUEUE_CONCURRENCY = 1;

export const LOG_THROTTLE_MS = 5000;

export const TORRENT_CONNECT_TIMEOUT_MS = 30000;

export const TORRENT_TRACKERS = [
  'http://bt.3kb.xyz:80/announce',
  'http://h4.trakx.nibba.trade:80/announce',
  'http://novaopcj.icu:10325/announce',
  'http://open.trackerlist.xyz:80/announce',
  'http://publictracker.ch:6969/announce',
  'http://retracker.sevstar.net:2710/announce',
  'http://retracker.telecom.by:80/announce',
  'http://rt.tace.ru:80/announce',
  'http://t.nyaatracker.com:80/announce',
  'http://tracker.noobsubs.net:80/announce',
  'http://tracker.openbittorrent.com:80/announce',
  'http://tracker.sakurato.xyz:23333/announce',
  'http://tracker.tfile.cc/announce',
  'http://tracker.tfile.me/announce',
  'http://tracker.torrentyorg.pl:80/announce',
  'http://tracker1.bt.moack.co.kr:80/announce',
  'http://tracker2.itzmx.com:6961/announce',
  'http://tracker3.itzmx.com:6961/announce',
  'http://vps02.net.orel.ru:80/announce',
  'https://1337.abcvg.info:443/announce',
  'https://tracker.imgoingto.icu:443/announce',
  'https://tracker.lilithraws.cf:443/announce',
  'https://tracker.nitrix.me:443/announce',
  'https://tracker.tamersunion.org:443/announce',
  'https://trakx.herokuapp.com:443/announce',
  'udp://3rt.tace.ru:60889/announce',
  'udp://47.ip-51-68-199.eu:6969/announce',
  'udp://61626c.net:6969/announce',
  'udp://aaa.army:8866/announce',
  'udp://adm.category5.tv:6969/announce',
  'udp://admin.videoenpoche.info:6969/announce',
  'udp://adminion.n-blade.ru:6969/announce',
  'udp://api.bitumconference.ru:6969/announce',
  'udp://aruacfilmes.com.br:6969/announce',
  'udp://benouworldtrip.fr:6969/announce',
  'udp://bioquantum.co.za:6969/announce',
  'udp://bms-hosxp.com:6969/announce',
  'udp://blokas.io:6969/announce',
  'udp://bt1.archive.org:6969/announce',
  'udp://bt2.archive.org:6969/announce',
  'udp://cdn-1.gamecoast.org:6969/announce',
  'udp://cdn-2.gamecoast.org:6969/announce',
  'udp://chanchan.uchuu.co.uk:6969/announce',
  'udp://code2chicken.nl:6969/announce',
  'udp://daveking.com:6969/announce',
  'udp://discord.heihachi.pw:6969/announce',
  'udp://dpiui.reedlan.com:6969/announce',
  'udp://edu.uifr.ru:6969/announce',
  'udp://engplus.ru:6969/announce',
  'udp://explodie.org:6969/announce',
  'udp://forever-tracker.zooki.xyz:6969/announce',
  'udp://free-tracker.zooki.xyz:6969/announce',
  'udp://git.vulnix.sh:6969/announce',
  'udp://inferno.demonoid.is:3391/announce',
  'udp://ipv4.tracker.harry.lu:80/announce',
  'udp://kanal-4.de:6969/announce',
  'udp://koli.services:6969/announce',
  'udp://line-net.ru:6969/announce',
  'udp://ln.mtahost.co:6969/announce',
  'udp://mail.realliferpg.de:6969/announce',
  'udp://movies.zsw.ca:6969/announce',
  'udp://mts.tvbit.co:6969/announce',
  'udp://nagios.tks.sumy.ua:80/announce',
  'udp://opentor.org:2710/announce',
  'udp://opentracker.i2p.rocks:6969/announce',
  'udp://publictracker.xyz:6969/announce',
  'udp://retracker.akado-ural.ru:80/announce',
  'udp://retracker.lanta-net.ru:2710/announce',
  'udp://rutorrent.frontline-mod.com:6969/announce',
  'udp://sd-161673.dedibox.fr:6969/announce',
  'udp://storage.groupees.com:6969/announce',
  'udp://t1.leech.ie:1337/announce',
  'udp://t2.leech.ie:1337/announce',
  'udp://t3.leech.ie:1337/announce',
  'udp://teamspeak.value-wolf.org:6969/announce',
  'udp://torrent.tdjs.tech:6969/announce',
  'udp://tracker.0x.tf:6969/announce',
  'udp://tracker.army:6969/announce',
  'udp://tracker.blacksparrowmedia.net:6969/announce',
  'udp://tracker.bt4g.com:2095/announce',
  'udp://tracker.cyberia.is:6969/announce',
  'udp://tracker.dler.org:6969/announce',
  'udp://tracker.ds.is:6969/announce',
  'udp://tracker.dyne.org:6969/announce',
  'udp://tracker.fortu.io:6969/announce',
  'udp://tracker.internetwarriors.net:1337/announce',
  'udp://tracker.kamigami.org:2710/announce',
  'udp://tracker.lilithraws.org:233/announce',
  'udp://tracker.moeking.me:6969/announce',
  'udp://tracker.open-internet.nl:6969/announce',
  'udp://tracker.openbittorrent.com:6969/announce',
  'udp://tracker.opentrackr.org:1337/announce',
  'udp://tracker.pirateparty.gr:6969/announce',
  'udp://tracker.publictracker.xyz:6969/announce',
  'udp://tracker.shkinev.me:6969/announce',
  'udp://tracker.v6speed.org:6969/announce',
  'udp://www.midea123.z-media.com.cn:6969/announce',
];

export const VIDEO_FILE_EXT = ['.mp4', '.mkv', '.avi', '.mov', '.wmv'];
